default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: postgres
  username: pguser
  password: pgpassword

development:
  <<: *default
  database: live_chat_app_development

test:
  <<: *default
  database: live_chat_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: live_chat_app_production
  username: live_chat_app
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
