source 'https://rubygems.org'
git_source(:github) { |_repo| "https://github.com/#{repo}.git" }

ruby '3.1.4'

gem 'active_model_serializers', '0.10.14'
gem 'bootsnap', require: false
gem 'devise'
gem 'devise_token_auth'
gem 'pg', '1.5.6'
gem 'puma', '6.4.2'
gem 'rack-cors', '2.0.2'
gem 'rails', '7.0.8'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

group :development, :test do
  gem 'byebug', '11.1.3'
  gem 'capybara', '3.40.0'
  gem 'factory_bot_rails', '6.4.3'
  gem 'pry-byebug', '3.10.1'
  gem 'pry-doc', '1.5.0'
  gem 'pry-rails', '0.3.9'
  gem 'pry-stack_explorer', '0.6.1'
  gem 'rspec-rails', '6.1.2'
  gem 'rspec-request_describer', '0.5.0'
end

group :development do
  gem 'rubocop', require: false
  gem 'rubocop-capybara', require: false
  gem 'rubocop-factory_bot', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
end
